
    path("admin/changelog/",TemplateView.as_view(template_name="admin/contents/changelog.html"),name="changelog"),
    path("admin/form_actions/",TemplateView.as_view(template_name="admin/contents/form_actions.html"),name="form_actions"),
    path("admin/form_checkboxes_radios/",TemplateView.as_view(template_name="admin/contents/form_checkboxes_radios.html"),
    name="form_chbx_radio"),
    path("admin/form_controls_extended/",TemplateView.as_view(template_name="admin/contents/form_controls_extended.html"),
    name="form_controls_extd"),
    path("admin/form_inputs/",TemplateView.as_view(template_name="admin/contents/form_inputs.html"),
    name="form_inputs"),
    path("admin/forms_select2/",TemplateView.as_view(template_name="admin/contents/form_select2.html"),
    name="form_select2"),
    path("admin/form_multiselect/",TemplateView.as_view(template_name="admin/contents/form_multiselect.html"),
    name="form_multiselect"),
    path("admin/form_input_groups/",TemplateView.as_view(template_name="admin/contents/form_input_groups.html"),
    name="form_input_groups"),
    path("admin/form_controls_extended/",TemplateView.as_view(template_name="admin/contents/form_controls_extended.html"),
    name="form_controls_extended"),
    path("admin/form_floating_labels/",TemplateView.as_view(template_name="admin/contents/form_floating_labels.html"),
    name="form_floating_labels"),
    path("admin/form_tag_inputs/",TemplateView.as_view(template_name="admin/contents/form_tag_inputs.html"),
    name="form_tag_inputs"),
    path("admin/form_dual_listboxes/",TemplateView.as_view(template_name="admin/contents/form_dual_listboxes.html"),
    name="form_dual_listboxes"),
    path("admin/form_validation/",TemplateView.as_view(template_name="admin/contents/form_validation.html"),
    name="form_validation"),
    path("admin/form_wizard/",TemplateView.as_view(template_name="admin/contents/form_wizard.html"),
    name="form_wizard"),
    path("admin/form_inputs_grid/",TemplateView.as_view(template_name="admin/contents/form_inputs_grid.html"),
    name="form_inputs_grid"),

    path("admin/alpaca_basic/",TemplateView.as_view(template_name="admin/contents/alpaca_basic.html"),
    name="alpaca_basic"),
    path("admin/alpaca_advanced/",TemplateView.as_view(template_name="admin/contents/alpaca_advanced.html"),
    name="alpaca_advanced"),
    path("admin/alpaca_controls/",TemplateView.as_view(template_name="admin/contents/alpaca_controls.html"),
    name="alpaca_controls"),

    path("admin/editor_summernote/",TemplateView.as_view(template_name="admin/contents/editor_summernote.html"),
    name="editor_summernote"),
    path("admin/editor_ckeditor/",TemplateView.as_view(template_name="admin/contents/editor_ckeditor.html"),
    name="editor_ckeditor"),
    path("admin/editor_trumbowyg/",TemplateView.as_view(template_name="admin/contents/editor_trumbowyg.html"),
    name="editor_trumbowyg"),
    path("admin/editor_code/",TemplateView.as_view(template_name="admin/contents/editor_code.html"),
    name="editor_code"),

    path("admin/picker_date/",TemplateView.as_view(template_name="admin/contents/picker_date.html"),
    name="picker_date"),
    path("admin/picker_color/",TemplateView.as_view(template_name="admin/contents/picker_color.html"),
    name="picker_color"),
    path("admin/picker_location/",TemplateView.as_view(template_name="admin/contents/picker_location.html"),
    name="picker_location"),

    path("admin/form_layout_vertical/",TemplateView.as_view(template_name="admin/contents/form_layout_vertical.html"),
    name="form_layout_vertical"),
    path("admin/form_layout_horizontal/",TemplateView.as_view(template_name="admin/contents/form_layout_horizontal.html"),
    name="form_layout_horizontal"),
    # Components
    path("admin/components_modals/",TemplateView.as_view(template_name="admin/contents/components_modals.html"),
    name="components_modals"),
    path("admin/components_dropdowns/",TemplateView.as_view(template_name="admin/contents/components_dropdowns.html"),
    name="components_dropdowns"),
    path("admin/components_tabs/",TemplateView.as_view(template_name="admin/contents/components_tabs.html"),
    name="components_tabs"),
    path("admin/components_pills/",TemplateView.as_view(template_name="admin/contents/components_pills.html"),
    name="components_pills"),
    path("admin/components_collapsible/",TemplateView.as_view(template_name="admin/contents/components_collapsible.html"),
    name="components_collapsible"),
    path("admin/components_navs/",TemplateView.as_view(template_name="admin/contents/components_navs.html"),
    name="components_navs"),
    path("admin/components_buttons/",TemplateView.as_view(template_name="admin/contents/components_buttons.html"),
    name="components_buttons"),
    path("admin/components_popups/",TemplateView.as_view(template_name="admin/contents/components_popups.html"),
    name="components_popups"),
    path("admin/components_alerts/",TemplateView.as_view(template_name="admin/contents/components_alerts.html"),
    name="components_alerts"),
    path("admin/components_pagination/",TemplateView.as_view(template_name="admin/contents/components_pagination.html"),
    name="components_pagination"),
    path("admin/components_badges/",TemplateView.as_view(template_name="admin/contents/components_badges.html"),
    name="components_badges"),
    path("admin/components_progress/",TemplateView.as_view(template_name="admin/contents/components_progress.html"),
    name="components_progress"),
    path("admin/components_scrollspy/",TemplateView.as_view(template_name="admin/contents/components_scrollspy.html"),
    name="components_scrollspy"),
    path("admin/components_breadcrumbs/",TemplateView.as_view(template_name="admin/contents/components_breadcrumbs.html"),
    name="components_breadcrumbs"),
    path("admin/components_media/",TemplateView.as_view(template_name="admin/contents/components_media.html"),
    name="components_media"),
    # Content
    path("admin/content_page_header/",TemplateView.as_view(template_name="admin/contents/content_page_header.html"),
    name="content_page_header"),
    path("admin/content_cards/",TemplateView.as_view(template_name="admin/contents/content_cards.html"),
    name="content_cards"),
    path("admin/content_cards_content/",TemplateView.as_view(template_name="admin/contents/content_cards_content.html"),
    name="content_cards_content"),
    path("admin/content_cards_layouts/",TemplateView.as_view(template_name="admin/contents/content_cards_layouts.html"),
    name="content_cards_layouts"),
    path("admin/content_cards_header/",TemplateView.as_view(template_name="admin/contents/content_cards_header.html"),
    name="content_cards_header"),
    path("admin/content_cards_footer/",TemplateView.as_view(template_name="admin/contents/content_cards_footer.html"),
    name="content_cards_footer"),
    path("admin/content_cards_draggable/",TemplateView.as_view(template_name="admin/contents/content_cards_draggable.html"),
    name="content_cards_draggable"),
    path("admin/content_text_styling/",TemplateView.as_view(template_name="admin/contents/content_text_styling.html"),
    name="content_text_styling"),
    path("admin/content_typography/",TemplateView.as_view(template_name="admin/contents/content_typography.html"),
    name="content_typography"),
    path("admin/content_helpers/",TemplateView.as_view(template_name="admin/contents/content_helpers.html"),
    name="content_helpers"),
    path("admin/content_helpers_flex/",TemplateView.as_view(template_name="admin/contents/content_helpers_flex.html"),
    name="content_helpers_flex"),
    path("admin/content_syntax_highlighter/",TemplateView.as_view(template_name="admin/contents/content_syntax_highlighter.html"),
    name="content_syntax_highlighter"),
    path("admin/content_grid/",TemplateView.as_view(template_name="admin/contents/content_grid.html"),
    name="content_grid"),

    # Extras
    path("admin/extra_pnotify/",TemplateView.as_view(template_name="admin/contents/extra_pnotify.html"),
    name="extra_pnotify"),
    path("admin/extra_jgrowl_noty/",TemplateView.as_view(template_name="admin/contents/extra_jgrowl_noty.html"),
    name="extra_jgrowl_noty"),
    path("admin/extra_sweetalert/",TemplateView.as_view(template_name="admin/contents/extra_sweetalert.html"),
    name="extra_sweetalert"),
    path("admin/extra_sliders_noui/",TemplateView.as_view(template_name="admin/contents/extra_sliders_noui.html"),
    name="extra_sliders_noui"),
    path("admin/extra_sliders_ion/",TemplateView.as_view(template_name="admin/contents/extra_sliders_ion.html"),
    name="extra_sliders_ion"),
    path("admin/extra_trees/",TemplateView.as_view(template_name="admin/contents/extra_trees.html"),
    name="extra_trees"),
    path("admin/extra_context_menu/",TemplateView.as_view(template_name="admin/contents/extra_context_menu.html"),
    name="extra_context_menu"),
    path("admin/extra_fab/",TemplateView.as_view(template_name="admin/contents/extra_fab.html"),
    name="extra_fab"),
    path("admin/extra_session_timeout/",TemplateView.as_view(template_name="admin/contents/extra_session_timeout.html"),
    name="extra_session_timeout"),
    path("admin/extra_idle_timeout/",TemplateView.as_view(template_name="admin/contents/extra_idle_timeout.html"),
    name="extra_idle_timeout"),

    # Colors
    path("admin/colors_primary/",TemplateView.as_view(template_name="admin/contents/colors_primary.html"),
    name="colors_primary"),
    path("admin/colors_danger/",TemplateView.as_view(template_name="admin/contents/colors_danger.html"),
    name="colors_danger"),
    path("admin/colors_success/",TemplateView.as_view(template_name="admin/contents/colors_success.html"),
    name="colors_success"),
    path("admin/colors_warning/",TemplateView.as_view(template_name="admin/contents/colors_warning.html"),
    name="colors_warning"),
    path("admin/colors_info/",TemplateView.as_view(template_name="admin/contents/colors_info.html"),
    name="colors_info"),
    path("admin/colors_pink/",TemplateView.as_view(template_name="admin/contents/colors_pink.html"),
    name="colors_pink"),
    path("admin/colors_violet/",TemplateView.as_view(template_name="admin/contents/colors_violet.html"),
    name="colors_violet"),
    path("admin/colors_purple/",TemplateView.as_view(template_name="admin/contents/colors_purple.html"),
    name="colors_purple"),
    path("admin/colors_indigo/",TemplateView.as_view(template_name="admin/contents/colors_indigo.html"),
    name="colors_indigo"),
    path("admin/colors_blue/",TemplateView.as_view(template_name="admin/contents/colors_blue.html"),
    name="colors_blue"),
    path("admin/colors_teal/",TemplateView.as_view(template_name="admin/contents/colors_teal.html"),
    name="colors_teal"),
    path("admin/colors_brown/",TemplateView.as_view(template_name="admin/contents/colors_brown.html"),
    name="colors_brown"),
    path("admin/colors_green/",TemplateView.as_view(template_name="admin/contents/colors_green.html"),
    name="colors_green"),
    path("admin/colors_orange/",TemplateView.as_view(template_name="admin/contents/colors_orange.html"),
    name="colors_orange"),
    path("admin/colors_grey/",TemplateView.as_view(template_name="admin/contents/colors_grey.html"),
    name="colors_grey"),
    path("admin/colors_slate/",TemplateView.as_view(template_name="admin/contents/colors_slate.html"),
    name="colors_slate"),

    # Animations
    path("admin/animations_css3/",TemplateView.as_view(template_name="admin/contents/animations_css3.html"),
    name="animations_css3"),
    path("admin/animations_velocity_basic/",TemplateView.as_view(template_name="admin/contents/animations_velocity_basic.html"),
    name="animations_velocity_basic"),
    path("admin/animations_velocity_ui/",TemplateView.as_view(template_name="admin/contents/animations_velocity_ui.html"),
    name="animations_velocity_ui"),
    path("admin/animations_velocity_examples/",TemplateView.as_view(template_name="admin/contents/animations_velocity_examples.html"),
    name="animations_velocity_examples"),
    #  Icons
    path("admin/icons_icomoon/",TemplateView.as_view(template_name="admin/contents/icons_icomoon.html"),
    name="icons_icomoon"),
    path("admin/icons_material/",TemplateView.as_view(template_name="admin/contents/icons_material.html"),
    name="icons_material"),
    path("admin/icons_fontawesome/",TemplateView.as_view(template_name="admin/contents/icons_fontawesome.html"),
    name="icons_fontawesome"),
    # Echarts
    path("admin/echarts_lines/",TemplateView.as_view(template_name="admin/contents/echarts_lines.html"),
    name="echarts_lines"),
    path("admin/echarts_areas/",TemplateView.as_view(template_name="admin/contents/echarts_areas.html"),
    name="echarts_areas"),
    path("admin/echarts_columns_waterfalls/",TemplateView.as_view(template_name="admin/contents/echarts_columns_waterfalls.html"),
    name="echarts_columns_waterfalls"),
    path("admin/echarts_bars_tornados/",TemplateView.as_view(template_name="admin/contents/echarts_bars_tornados.html"),
    name="echarts_bars_tornados"),
    path("admin/echarts_scatter/",TemplateView.as_view(template_name="admin/contents/echarts_scatter.html"),
    name="echarts_scatter"),
    path("admin/echarts_pies_donuts/",TemplateView.as_view(template_name="admin/contents/echarts_pies_donuts.html"),
    name="echarts_pies_donuts"),
    path("admin/echarts_funnels_calendars/",TemplateView.as_view(template_name="admin/contents/echarts_funnels_calendars.html"),
    name="echarts_funnels_calendars"),
    path("admin/echarts_candlesticks_others/",TemplateView.as_view(template_name="admin/contents/echarts_candlesticks_others.html"),
    name="echarts_candlesticks_others"),
    # D3 - charts
    path("admin/d3_lines_basic/",TemplateView.as_view(template_name="admin/contents/d3_lines_basic.html"),
    name="d3_lines_basic"),
    path("admin/d3_lines_advanced/",TemplateView.as_view(template_name="admin/contents/d3_lines_advanced.html"),
    name="d3_lines_advanced"),
    path("admin/d3_bars_basic/",TemplateView.as_view(template_name="admin/contents/d3_bars_basic.html"),
    name="d3_bars_basic"),
    path("admin/d3_bars_advanced/",TemplateView.as_view(template_name="admin/contents/d3_bars_advanced.html"),
    name="d3_bars_advanced"),
    path("admin/d3_pies/",TemplateView.as_view(template_name="admin/contents/d3_pies.html"),
    name="d3_pies"),
    path("admin/d3_circle_diagrams/",TemplateView.as_view(template_name="admin/contents/d3_circle_diagrams.html"),
    name="d3_circle_diagrams"),
    path("admin/d3_tree/",TemplateView.as_view(template_name="admin/contents/d3_tree.html"),
    name="d3_tree"),
    path("admin/d3_other/",TemplateView.as_view(template_name="admin/contents/d3_other.html"),
    name="d3_other"),
    # C3 - charts
    path("admin/c3_lines_areas/",TemplateView.as_view(template_name="admin/contents/c3_lines_areas.html"),
    name="c3_lines_areas"),
    path("admin/c3_bars_pies/",TemplateView.as_view(template_name="admin/contents/c3_bars_pies.html"),
    name="c3_bars_pies"),
    path("admin/c3_advanced/",TemplateView.as_view(template_name="admin/contents/c3_advanced.html"),
    name="c3_advanced"),
    path("admin/c3_axis/",TemplateView.as_view(template_name="admin/contents/c3_axis.html"),
    name="c3_axis"),
    path("admin/c3_grid/",TemplateView.as_view(template_name="admin/contents/c3_grid.html"),
    name="c3_grid"),

    #map integration
    path("admin/maps_vector/",TemplateView.as_view(template_name="admin/contents/maps_vector.html"),
    name="maps_vector"),
    # Extension
    path("admin/extension_image_cropper/",TemplateView.as_view(template_name="admin/contents/extension_image_cropper.html"),
    name="extension_image_cropper"),
    path("admin/extension_blockui/",TemplateView.as_view(template_name="admin/contents/extension_blockui.html"),
    name="extension_blockui"),
    path("admin/extension_dnd/",TemplateView.as_view(template_name="admin/contents/extension_dnd.html"),
    name="extension_dnd"),

    # JQueryUI
    path("admin/jqueryui_interactions/",TemplateView.as_view(template_name="admin/contents/jqueryui_interactions.html"),
    name="jqueryui_interactions"),
    path("admin/jqueryui_forms/",TemplateView.as_view(template_name="admin/contents/jqueryui_forms.html"),
    name="jqueryui_forms"),
    path("admin/jqueryui_components/",TemplateView.as_view(template_name="admin/contents/jqueryui_components.html"),
    name="jqueryui_components"),
    path("admin/jqueryui_sliders/",TemplateView.as_view(template_name="admin/contents/jqueryui_sliders.html"),
    name="jqueryui_sliders"),
    path("admin/jqueryui_navigation/",TemplateView.as_view(template_name="admin/contents/jqueryui_navigation.html"),
    name="jqueryui_navigation"),

    # uploader
    path("admin/uploader_plupload/",TemplateView.as_view(template_name="admin/contents/uploader_plupload.html"),
    name="uploader_plupload"),
    path("admin/uploader_bootstrap/",TemplateView.as_view(template_name="admin/contents/uploader_bootstrap.html"),
    name="uploader_bootstrap"),
    path("admin/uploader_dropzone/",TemplateView.as_view(template_name="admin/contents/uploader_dropzone.html"),
    name="uploader_dropzone"),

    # Full Calendar
    path("admin/fullcalendar_views/",TemplateView.as_view(template_name="admin/contents/fullcalendar_views.html"),
    name="fullcalendar_views"),
    path("admin/fullcalendar_styling/",TemplateView.as_view(template_name="admin/contents/fullcalendar_styling.html"),
    name="fullcalendar_styling"),
    path("admin/fullcalendar_formats/",TemplateView.as_view(template_name="admin/contents/fullcalendar_formats.html"),
    name="fullcalendar_formats"),
    path("admin/fullcalendar_advanced/",TemplateView.as_view(template_name="admin/contents/fullcalendar_advanced.html"),
    name="fullcalendar_advanced"),

    # I18n
    path("admin/internationalization_switch_direct/",TemplateView.as_view(template_name="admin/contents/internationalization_switch_direct.html"),
    name="internationalization_switch_direct"),
    path("admin/internationalization_switch_query/",TemplateView.as_view(template_name="admin/contents/internationalization_switch_query.html"),
    name="internationalization_switch_query"),
    path("admin/internationalization_fallback/",TemplateView.as_view(template_name="admin/contents/internationalization_fallback.html"),
    name="internationalization_fallback"),
    path("admin/internationalization_callbacks/",TemplateView.as_view(template_name="admin/contents/internationalization_callbacks.html"),
    name="internationalization_callbacks"),

    # Table
    path("admin/table_basic/",TemplateView.as_view(template_name="admin/contents/table_basic.html"),
    name="table_basic"),
    path("admin/table_sizing/",TemplateView.as_view(template_name="admin/contents/table_sizing.html"),
    name="table_sizing"),
    path("admin/table_borders/",TemplateView.as_view(template_name="admin/contents/table_borders.html"),
    name="table_borders"),
    path("admin/table_styling/",TemplateView.as_view(template_name="admin/contents/table_styling.html"),
    name="table_styling"),
    path("admin/table_elements/",TemplateView.as_view(template_name="admin/contents/table_elements.html"),
    name="table_elements"),

    # Datatables
    path("admin/datatable_basic/",TemplateView.as_view(template_name="admin/contents/datatable_basic.html"),
    name="datatable_basic"),
    path("admin/datatable_styling/",TemplateView.as_view(template_name="admin/contents/datatable_styling.html"),
    name="datatable_styling"),
    path("admin/datatable_advanced/",TemplateView.as_view(template_name="admin/contents/datatable_advanced.html"),
    name="datatable_advanced"),
    path("admin/datatable_sorting/",TemplateView.as_view(template_name="admin/contents/datatable_sorting.html"),
    name="datatable_sorting"),
    path("admin/datatable_api/",TemplateView.as_view(template_name="admin/contents/datatable_api.html"),
    name="datatable_api"),
    path("admin/datatable_data_sources/",TemplateView.as_view(template_name="admin/contents/datatable_data_sources.html"),
    name="datatable_data_sources"),
    # Datatables extension
    path("admin/datatable_extension_reorder/",TemplateView.as_view(template_name="admin/contents/datatable_extension_reorder.html"),
    name="datatable_extension_reorder"),
    path("admin/datatable_extension_row_reorder/",TemplateView.as_view(template_name="admin/contents/datatable_extension_row_reorder.html"),
    name="datatable_extension_row_reorder"),
    path("admin/datatable_extension_fixed_columns/",TemplateView.as_view(template_name="admin/contents/datatable_extension_fixed_columns.html"),
    name="datatable_extension_fixed_columns"),
    path("admin/datatable_extension_fixed_header/",TemplateView.as_view(template_name="admin/contents/datatable_extension_fixed_header.html"),
    name="datatable_extension_fixed_header"),
    path("admin/datatable_extension_autofill/",TemplateView.as_view(template_name="admin/contents/datatable_extension_autofill.html"),
    name="datatable_extension_autofill"),
    path("admin/datatable_extension_key_table/",TemplateView.as_view(template_name="admin/contents/datatable_extension_key_table.html"),
    name="datatable_extension_key_table"),
    path("admin/datatable_extension_scroller/",TemplateView.as_view(template_name="admin/contents/datatable_extension_scroller.html"),
    name="datatable_extension_scroller"),
    path("admin/datatable_extension_select/",TemplateView.as_view(template_name="admin/contents/datatable_extension_select.html"),
    name="datatable_extension_select"),
    path("admin/datatable_extension_buttons_init/",TemplateView.as_view(template_name="admin/contents/datatable_extension_buttons_init.html"),
    name="datatable_extension_buttons_init"),
    path("admin/datatable_extension_buttons_flash/",TemplateView.as_view(template_name="admin/contents/datatable_extension_buttons_flash.html"),
    name="datatable_extension_buttons_flash"),
    path("admin/datatable_extension_buttons_print/",TemplateView.as_view(template_name="admin/contents/datatable_extension_buttons_print.html"),
    name="datatable_extension_buttons_print"),
    path("admin/datatable_extension_buttons_html5/",TemplateView.as_view(template_name="admin/contents/datatable_extension_buttons_html5.html"),
    name="datatable_extension_buttons_html5"),
    path("admin/datatable_extension_colvis/",TemplateView.as_view(template_name="admin/contents/datatable_extension_colvis.html"),
    name="datatable_extension_colvis"),

    # Hadsontable
    path("admin/handsontable_basic/",TemplateView.as_view(template_name="admin/contents/handsontable_basic.html"),
    name="handsontable_basic"),
    path("admin/handsontable_advanced/",TemplateView.as_view(template_name="admin/contents/handsontable_advanced.html"),
    name="handsontable_advanced"),
    path("admin/handsontable_cols/",TemplateView.as_view(template_name="admin/contents/handsontable_cols.html"),
    name="handsontable_cols"),
    path("admin/handsontable_cells/",TemplateView.as_view(template_name="admin/contents/handsontable_cells.html"),
    name="handsontable_cells"),
    path("admin/handsontable_types/",TemplateView.as_view(template_name="admin/contents/handsontable_types.html"),
    name="handsontable_types"),
    path("admin/handsontable_custom_checks/",TemplateView.as_view(template_name="admin/contents/handsontable_custom_checks.html"),
    name="handsontable_custom_checks"),
    path("admin/handsontable_ac_password/",TemplateView.as_view(template_name="admin/contents/handsontable_ac_password.html"),
    name="handsontable_ac_password"),
    path("admin/handsontable_search/",TemplateView.as_view(template_name="admin/contents/handsontable_search.html"),
    name="handsontable_search"),
    path("admin/handsontable_context/",TemplateView.as_view(template_name="admin/contents/handsontable_context.html"),
    name="handsontable_context"),
    # Responsive
    path("admin/table_responsive/",TemplateView.as_view(template_name="admin/contents/table_responsive.html"),
    name="table_responsive"),
    path("admin/datatable_responsive/",TemplateView.as_view(template_name="admin/contents/datatable_responsive.html"),
    name="datatable_responsive"),
    # General
    path("admin/general_feed/",TemplateView.as_view(template_name="admin/contents/general_feed.html"),
    name="general_feed"),
    path("admin/general_embeds/",TemplateView.as_view(template_name="admin/contents/general_embeds.html"),
    name="general_embeds"),
    path("admin/general_faq/",TemplateView.as_view(template_name="admin/contents/general_faq.html"),
    name="general_faq"),
    path("admin/general_knowledgebase/",TemplateView.as_view(template_name="admin/contents/general_knowledgebase.html"),
    name="general_knowledgebase"),

    # blog
    path("admin/blog_classic_v/",TemplateView.as_view(template_name="admin/contents/blog_classic_v.html"),
    name="blog_classic_v"),
    path("admin/blog_classic_h/",TemplateView.as_view(template_name="admin/contents/blog_classic_h.html"),
    name="blog_classic_h"),
    path("admin/blog_grid/",TemplateView.as_view(template_name="admin/contents/blog_grid.html"),
    name="blog_grid"),
    path("admin/blog_single/",TemplateView.as_view(template_name="admin/contents/blog_single.html"),
    name="blog_single"),
    path("admin/blog_sidebar_left/",TemplateView.as_view(template_name="admin/contents/blog_sidebar_left.html"),
    name="blog_sidebar_left"),
    path("admin/blog_sidebar_right/",TemplateView.as_view(template_name="admin/contents/blog_sidebar_right.html"),
    name="blog_sidebar_right"),

    # Timelines
    path("admin/timelines_left/",TemplateView.as_view(template_name="admin/contents/timelines_left.html"),
    name="timelines_left"),
    path("admin/timelines_right/",TemplateView.as_view(template_name="admin/contents/timelines_right.html"),
    name="timelines_right"),
    path("admin/timelines_center/",TemplateView.as_view(template_name="admin/contents/timelines_center.html"),
    name="timelines_center"),
    # GAllery
    path("admin/gallery_grid/",TemplateView.as_view(template_name="admin/contents/gallery_grid.html"),
    name="gallery_grid"),
    path("admin/gallery_titles/",TemplateView.as_view(template_name="admin/contents/gallery_titles.html"),
    name="gallery_titles"),
    path("admin/gallery_description/",TemplateView.as_view(template_name="admin/contents/gallery_description.html"),
    name="gallery_description"),
    path("admin/gallery_library/",TemplateView.as_view(template_name="admin/contents/gallery_library.html"),
    name="gallery_library"),
     # Invoicd
    path("admin/invoice_template/",TemplateView.as_view(template_name="admin/contents/invoice_template.html"),
    name="invoice_template"),
    path("admin/invoice_grid/",TemplateView.as_view(template_name="admin/contents/invoice_grid.html"),
    name="invoice_grid"),
    path("admin/invoice_archive/",TemplateView.as_view(template_name="admin/contents/invoice_archive.html"),
    name="invoice_archive"),
    # errors
    path("admin/error_403/",TemplateView.as_view(template_name="admin/contents/error_403.html"),
    name="error_403"),
    path("admin/error_404/",TemplateView.as_view(template_name="admin/contents/error_404.html"),
    name="error_404"),
    path("admin/error_405/",TemplateView.as_view(template_name="admin/contents/error_405.html"),
    name="error_405"),
    path("admin/error_500/",TemplateView.as_view(template_name="admin/contents/error_500.html"),
    name="error_500"),
    path("admin/error_503/",TemplateView.as_view(template_name="admin/contents/error_503.html"),
    name="error_503"),
    path("admin/error_offline/",TemplateView.as_view(template_name="admin/contents/error_offline.html"),
    name="error_offline"),
    # Userpages
    path("admin/user_pages_list/",TemplateView.as_view(template_name="admin/contents/user_pages_list.html"),
    name="user_pages_list"),
    path("admin/user_pages_cards/",TemplateView.as_view(template_name="admin/contents/user_pages_cards.html"),
    name="user_pages_cards"),
    path("admin/user_pages_profile/",TemplateView.as_view(template_name="admin/contents/user_pages_profile.html"),
    name="user_pages_profile"),
    path("admin/user_pages_profile_tabbed/",TemplateView.as_view(template_name="admin/contents/user_pages_profile_tabbed.html"),
    name="user_pages_profile_tabbed"),
    path("admin/user_pages_profile_cover/",TemplateView.as_view(template_name="admin/contents/user_pages_profile_cover.html"),
    name="user_pages_profile_cover"),
    # taskmanager
    path("admin/task_manager_grid/",TemplateView.as_view(template_name="admin/contents/task_manager_grid.html"),
    name="task_manager_grid"),
    path("admin/task_manager_list/",TemplateView.as_view(template_name="admin/contents/task_manager_list.html"),
    name="task_manager_list"),
    path("admin/task_manager_detailed/",TemplateView.as_view(template_name="admin/contents/task_manager_detailed.html"),
    name="task_manager_detailed"),
    # mail - list
    path("admin/mail_list/",TemplateView.as_view(template_name="admin/contents/mail_list.html"),
    name="mail_list"),
    path("admin/mail_list_detached/",TemplateView.as_view(template_name="admin/contents/mail_list_detached.html"),
    name="mail_list_detached"),
    path("admin/mail_read/",TemplateView.as_view(template_name="admin/contents/mail_read.html"),
    name="mail_read"),
    path("admin/mail_write/",TemplateView.as_view(template_name="admin/contents/mail_write.html"),
    name="mail_write"),
    path("admin/chat_layouts/",TemplateView.as_view(template_name="admin/contents/chat_layouts.html"),
    name="chat_layouts"),
    path("admin/chat_options/",TemplateView.as_view(template_name="admin/contents/chat_options.html"),
    name="chat_options"),
    # Search
    path("admin/search_basic/",TemplateView.as_view(template_name="admin/contents/search_basic.html"),
    name="search_basic"),
    path("admin/search_users/",TemplateView.as_view(template_name="admin/contents/search_users.html"),
    name="search_users"),
    path("admin/search_images/",TemplateView.as_view(template_name="admin/contents/search_images.html"),
    name="search_images"),
    path("admin/search_videos/",TemplateView.as_view(template_name="admin/contents/search_videos.html"),
    name="search_videos"),
    # Job list
    path("admin/job_list_cards/",TemplateView.as_view(template_name="admin/contents/job_list_cards.html"),
    name="job_list_cards"),
    path("admin/job_list_list/",TemplateView.as_view(template_name="admin/contents/job_list_list.html"),
    name="job_list_list"),
    path("admin/job_detailed/",TemplateView.as_view(template_name="admin/contents/job_detailed.html"),
    name="job_detailed"),
    path("admin/job_apply/",TemplateView.as_view(template_name="admin/contents/job_apply.html"),
    name="job_apply"),
    # Ecommerce
    path("admin/ecommerce_product_list/",TemplateView.as_view(template_name="admin/contents/ecommerce_product_list.html"),
    name="ecommerce_product_list"),
    path("admin/ecommerce_product_grid/",TemplateView.as_view(template_name="admin/contents/ecommerce_product_grid.html"),
    name="ecommerce_product_grid"),
    path("admin/ecommerce_orders_history/",TemplateView.as_view(template_name="admin/contents/ecommerce_orders_history.html"),
    name="ecommerce_orders_history"),
    path("admin/ecommerce_customers/",TemplateView.as_view(template_name="admin/contents/ecommerce_customers.html"),
    name="ecommerce_customers"),
    path("admin/ecommerce_pricing/",TemplateView.as_view(template_name="admin/contents/ecommerce_pricing.html"),
    name="ecommerce_pricing"),
    # widgets
    path("admin/widgets_content/",TemplateView.as_view(template_name="admin/contents/widgets_content.html"),
    name="widgets_content"),
    path("admin/widgets_stats/",TemplateView.as_view(template_name="admin/contents/widgets_stats.html"),
    name="widgets_stats"),