# Generated by Django 3.1.3 on 2021-01-14 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(max_length=200, verbose_name='Choice name (English)')),
                ('choice_name_am', models.CharField(max_length=200, verbose_name='Choice name(Amharic)')),
                ('description', models.TextField(verbose_name='Choice Description(English)')),
                ('description_am', models.TextField(verbose_name='Choice Description(Amharic)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollsQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Poll title (English)')),
                ('title_am', models.CharField(max_length=200, verbose_name='Poll title(Amharic)')),
                ('description', models.TextField(verbose_name='Poll Description(English)')),
                ('description_am', models.TextField(verbose_name='Poll Description(Amharic)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('choices', models.ManyToManyField(default='', related_name='choices', to='collaborations.Choices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(default='', max_length=200, verbose_name='Any remarks the user may have')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborations.choices')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborations.pollsquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'poll')},
            },
        ),
    ]
