# Generated by Django 3.1.3 on 2021-01-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0002_pollsquestion_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choice_name_em',
            new_name='choice_name_am',
        ),
    ]
