# Generated by Django 3.1.3 on 2021-01-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0003_auto_20210109_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsquestion',
            name='choices',
            field=models.ManyToManyField(blank='', default='', related_name='choices', to='collaborations.Choices'),
        ),
    ]
