# Generated by Django 3.1.3 on 2021-01-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0004_auto_20210110_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsquestion',
            name='choices',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='choices', to='collaborations.Choices'),
        ),
    ]
