# Generated by Django 3.1.3 on 2021-01-11 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborations', '0005_auto_20210110_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsquestion',
            name='choices',
            field=models.ManyToManyField(default='', related_name='choices', to='collaborations.Choices'),
        ),
        migrations.AlterField(
            model_name='pollsresult',
            name='remark',
            field=models.CharField(default='', max_length=200, verbose_name='Any remarks the user may have'),
        ),
        migrations.AlterUniqueTogether(
            name='pollsresult',
            unique_together={('user', 'poll')},
        ),
    ]
