# Generated by Django 3.1.2 on 2020-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by_admin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Company Name(English)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name_am',
            field=models.CharField(max_length=200, verbose_name='Company Name(Amharic)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='detail',
            field=models.TextField(verbose_name='Company Detail(English)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='detail_am',
            field=models.TextField(verbose_name='Company Detail(Amharic)'),
        ),
    ]
