# Generated by Django 3.1.2 on 2020-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201122_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Group'),
        ),
    ]
