# Generated by Django 3.1.3 on 2021-01-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210102_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadmin',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='companystaff',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
