# Generated by Django 3.1.3 on 2020-12-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_user_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group'),
        ),
    ]
