# Generated by Django 3.1.3 on 2020-12-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201201_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type_am',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
