# Generated by Django 3.1.3 on 2021-01-12 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title(English)')),
                ('title_am', models.CharField(max_length=200, verbose_name='Title(Amharic)')),
                ('description', models.TextField(verbose_name='Description(English)')),
                ('description_am', models.TextField(verbose_name='Description(Amharic)')),
                ('link', models.CharField(max_length=200, verbose_name='link')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name(English)')),
                ('company_name_am', models.CharField(max_length=200, verbose_name='Company Name(Amharic)')),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('detail', models.TextField(verbose_name='Company Detail(English)')),
                ('detail_am', models.TextField(verbose_name='Company Detail(Amharic)')),
                ('company_logo', models.ImageField(help_text='png,jpg,gif files, Max size 10MB', upload_to='', verbose_name='Company Logo')),
                ('company_intro', models.FileField(help_text='mp4,mkv,avi files, Max size 10MB', upload_to='', verbose_name='Company Logo')),
                ('company_type', models.CharField(max_length=255)),
                ('company_type_am', models.CharField(max_length=255)),
                ('number_of_employees', models.IntegerField(default=0, verbose_name='Number Of Employees')),
                ('established_year', models.IntegerField(default=0, verbose_name='Established Year')),
                ('certification', models.CharField(max_length=100, verbose_name='Certification')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('postal_code', models.CharField(default='', max_length=100, null=True)),
                ('products', models.CharField(default='', max_length=200, verbose_name='Main Products')),
                ('capital', models.FloatField(default=0)),
                ('incoterms', models.CharField(help_text='Incoterms', max_length=100, null=True, verbose_name='International Commercial Terms(English)')),
                ('incoterms_am', models.CharField(help_text='Incoterms', max_length=100, null=True, verbose_name='International Commercial Terms(Amharic)')),
                ('average_lead_time', models.CharField(max_length=100, null=True, verbose_name='Average Lead Time(Amharic)')),
                ('average_lead_time_am', models.CharField(max_length=100, null=True, verbose_name='Average Lead Time(Amharic)')),
                ('no_trading_staff', models.IntegerField(default=0, verbose_name='Number of Trading Staff')),
                ('terms_of_payment', models.CharField(max_length=100, null=True, verbose_name='Payment Method')),
                ('export_yr', models.IntegerField(default=0, null=True, verbose_name='Export Year')),
                ('export_percentage', models.FloatField(default=0, null=True, verbose_name='Export Percentage')),
                ('main_market', models.CharField(max_length=100, null=True, verbose_name='Main Market(English)')),
                ('main_market_am', models.CharField(max_length=100, null=True, verbose_name='Main Market(Amharic)')),
                ('nearest_port', models.CharField(max_length=100, null=True, verbose_name='Nearest Port(English)')),
                ('import_export', models.BooleanField(default=False)),
                ('r_and_d_capacity', models.CharField(max_length=100, null=True, verbose_name='R&D Capacity(English)')),
                ('r_and_d_capacity_am', models.CharField(max_length=100, null=True, verbose_name='R&D Capacity(Amharic)')),
                ('no_of_rnd_staff', models.IntegerField(default=0, null=True, verbose_name='Number of R&D Staff')),
                ('no_production_lines', models.IntegerField(default=0, null=True, verbose_name='Number Of Production Lines')),
                ('anual_op_value', models.CharField(max_length=100, null=True, verbose_name='Anual Output Value')),
                ('anual_op_main_products', models.TextField(verbose_name='Anual Output Value For Main Products(English)')),
                ('anual_op_main_products_am', models.TextField(verbose_name='Anual Output Value For Main Products(Amharic)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
