# Generated by Django 3.1.3 on 2021-01-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nearest_port_am',
            field=models.CharField(max_length=100, null=True, verbose_name='Nearest Port(Amharic)'),
        ),
    ]
