# Generated by Django 3.1.3 on 2021-01-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_nearest_port_am'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='anual_op_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anual Output Value'),
        ),
        migrations.AlterField(
            model_name='company',
            name='average_lead_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Average Lead Time(Amharic)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='average_lead_time_am',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Average Lead Time(Amharic)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_intro',
            field=models.FileField(help_text='mp4,mkv,avi files, Max size 10MB', upload_to='', verbose_name='Company Intro'),
        ),
        migrations.AlterField(
            model_name='company',
            name='export_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Export Percentage'),
        ),
        migrations.AlterField(
            model_name='company',
            name='export_yr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Export Year'),
        ),
        migrations.AlterField(
            model_name='company',
            name='incoterms',
            field=models.CharField(blank=True, help_text='Incoterms', max_length=100, null=True, verbose_name='International Commercial Terms(English)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='incoterms_am',
            field=models.CharField(blank=True, help_text='Incoterms', max_length=100, null=True, verbose_name='International Commercial Terms(Amharic)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='main_market',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Main Market(English)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='main_market_am',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Main Market(Amharic)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nearest_port',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nearest Port(English)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nearest_port_am',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nearest Port(Amharic)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='no_of_rnd_staff',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of R&D Staff'),
        ),
        migrations.AlterField(
            model_name='company',
            name='no_production_lines',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Of Production Lines'),
        ),
        migrations.AlterField(
            model_name='company',
            name='r_and_d_capacity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='R&D Capacity(English)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='r_and_d_capacity_am',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='R&D Capacity(Amharic)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='terms_of_payment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Method'),
        ),
    ]
