# Generated by Django 3.1.3 on 2021-01-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210112_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='anual_op_main_products',
            field=models.TextField(blank=True, null=True, verbose_name='Anual Output Value For Main Products(English)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='anual_op_main_products_am',
            field=models.TextField(blank=True, null=True, verbose_name='Anual Output Value For Main Products(Amharic)'),
        ),
    ]
