# Generated by Django 3.1.3 on 2021-01-13 07:12

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210112_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Your Company Theme'),
        ),
        migrations.AddField(
            model_name='companysolution',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companysolution',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CompanyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='Event Name(English)')),
                ('event_name_am', models.CharField(max_length=200, verbose_name='Event Name(Amharic)')),
                ('description', models.TextField(verbose_name='Description(English)')),
                ('description_am', models.TextField(verbose_name='Description(Amharic)')),
                ('image', models.ImageField(upload_to='')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
