# Generated by Django 3.1.3 on 2021-01-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210113_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='color',
            field=models.CharField(max_length=10, verbose_name='Your Company Theme'),
        ),
    ]
